npi-ufc-qxd/gpa-extensao

- aplicacao/gpa-extensao/.project
- aplicacao/gpa-extensao/.settings/org.eclipse.wst.common.component
- aplicacao/gpa-extensao/src/main/resources/application.properties
O projeto foi configurado para acessar o banco pelo jndi con figurado no
Tomcat.
Segue a configuração do Tomcat:
Server.xml:
```
<Resource auth="Container" driverClassName="org.postgresql.Driver"
name="gpa_extensao" password="postgres" type="javax.sql.DataSource"
url="jdbc:postgresql://localhost:5432/gpa_extensao"
username="postgres"/>
```
Context.xml:
```
<ResourceLink global="gpa_extensao" name="gpa_extensao"
type="javax.sql.DataSource"/>
```
> Configuração Jndi na aplicação

- aplicacao/gpa-extensao/src/main/java/ufc/quixada/npi/gpa/model/AcaoExtensao.java
- aplicacao/gpa-extensao/src/main/java/ufc/quixada/npi/gpa/model/Parecer.java
- aplicacao/gpa-extensao/src/main/java/ufc/quixada/npi/gpa/model/Participacao.java
- aplicacao/gpa-extensao/src/main/java/ufc/quixada/npi/gpa/repository/AcaoExtensao.java
- aplicacao/gpa-extensao/src/main/java/ufc/quixada/npi/gpa/repository/DocumentoRepository.java
- aplicacao/gpa-extensao/src/main/java/ufc/quixada/npi/gpa/repository/PapelRepository.java
- aplicacao/gpa-extensao/src/main/java/ufc/quixada/npi/gpa/repository/ParceiroRepository.java
- aplicacao/gpa-extensao/src/main/java/ufc/quixada/npi/gpa/repository/ParceriaExternaRepository.java
- aplicacao/gpa-extensao/src/main/java/ufc/quixada/npi/gpa/repository/ParecerRepository.java
- aplicacao/gpa-extensao/src/main/java/ufc/quixada/npi/gpa/repository/ParticipacaoRepository.java
- aplicacao/gpa-extensao/src/main/java/ufc/quixada/npi/gpa/repository/PessoaRepository.java
Model atualizada e repositórios básicos criados.
> Pesq 02 criando repository

- aplicacao/gpa-extensao/.project
- aplicacao/gpa-extensao/pom.xml
- aplicacao/gpa-extensao/src/main/java/ufc/quixada/npi/gpa/config/GpaExtensaoApplication.java
- aplicacao/gpa-extensao/src/main/java/ufc/quixada/npi/gpa/config/LdapConfig.java
- aplicacao/gpa-extensao/src/main/java/ufc/quixada/npi/gpa/config/SpringSecurityConfig.java
- aplicacao/gpa-extensao/src/main/java/ufc/quixada/npi/gpa/util/Constants.java
- aplicacao/gpa-extensao/src/main/resources/application.properties
Foi feita a configuração inicial do Spring Security para autenticação com
o LDAP.
> Configuração Spring Security

- aplicacao/gpa-extensao/pom.xml
- aplicacao/gpa-extensao/src/main/resources/application.properties
Foi configurado o caminho da pasta onde vão estar os arquivos da
aplicação.
> Configuração Inicial do AngularJS

- aplicacao/gpa-extensao/src/main/java/ufc/quixada/npi/gpa/controller/DirecaoController.java
- aplicacao/gpa-extensao/src/main/java/ufc/quixada/npi/gpa/controller/ExtensaoController.java
- aplicacao/gpa-extensao/src/main/java/ufc/quixada/npi/gpa/service/DirecaoService.java
- aplicacao/gpa-extensao/src/main/java/ufc/quixada/npi/gpa/service/impl/DirecaoServiceImpl.java
- aplicacao/gpa-extensao/src/main/java/ufc/quixada/npi/gpa/util/Constants.java
- aplicacao/gpa-extensao/src/main/resources/static/gpa/direcao/detalhes.js
- aplicacao/gpa-extensao/src/main/resources/templates/detalhes/acao/detalhes.html
- aplicacao/gpa-extensao/src/main/resources/templates/detalhes/acao/fragments.html
Foi implementada a funcionalidade de alterar o relator de uma ação de
extensão.
Além disso foram feitas algumas melhorias e padronizações no front-end.
> US22 - Alterar Relator

- aplicacao/gpa-extensao/src/main/resources/static/gpa/direcao/detalhes.js
- aplicacao/gpa-extensao/src/main/resources/templates/detalhes/acao/detalhes.html
- aplicacao/gpa-extensao/src/main/resources/templates/detalhes/acao/fragments-detalhes-parecer.html
Foram alguns testes e corrigidos alguns bugs.
> Tarefa finalizada

- aplicacao/gpa-extensao/src/main/java/ufc/quixada/npi/gpa/controller/DirecaoController.java
- aplicacao/gpa-extensao/src/main/java/ufc/quixada/npi/gpa/controller/ExtensaoController.java
- aplicacao/gpa-extensao/src/main/java/ufc/quixada/npi/gpa/repository/AcaoExtensaoRepository.java
- aplicacao/gpa-extensao/src/main/java/ufc/quixada/npi/gpa/util/Constants.java
- aplicacao/gpa-extensao/src/main/resources/templates/modulos/fragments.html
> Mostrar corretamente a quantidade de acoes do coordenador e em

- aplicacao/gpa-extensao/src/main/resources/static/gpa/modulos/menu.js
- aplicacao/gpa-extensao/src/main/resources/templates/coordenacao/crud/cadastrarExtensao.html
- aplicacao/gpa-extensao/src/main/resources/templates/direcao/index.html
- aplicacao/gpa-extensao/src/main/resources/templates/principal/index.html
Foram feitas algumas modificações e foi implementada a funcionalidade de
setar o item do menu como ativo ao ser clicado.
> EXT-65 Melhorias no menu

- aplicacao/gpa-extensao/src/main/java/ufc/quixada/npi/gpa/controller/ExtensaoController.java
- aplicacao/gpa-extensao/src/main/java/ufc/quixada/npi/gpa/repository/AcaoExtensaoRepository.java
- aplicacao/gpa-extensao/src/main/resources/templates/coordenacao/crud/cadastrarExtensao.html
> Permitir que uma ação só tenha vinculo com uma ação que já tenha sido

- aplicacao/gpa-extensao/pom.xml
- aplicacao/gpa-extensao/src/main/java/ufc/quixada/npi/gpa/controller/DocumentoController.java
- aplicacao/gpa-extensao/src/main/java/ufc/quixada/npi/gpa/model/DocumentoEntityListener.java
- aplicacao/gpa-extensao/src/main/java/ufc/quixada/npi/gpa/service/DocumentoService.java
- aplicacao/gpa-extensao/src/main/java/ufc/quixada/npi/gpa/service/impl/AcaoExtensaoServiceImpl.java
- aplicacao/gpa-extensao/src/main/java/ufc/quixada/npi/gpa/service/impl/DocumentoServiceImpl.java
- aplicacao/gpa-extensao/src/main/java/ufc/quixada/npi/gpa/service/impl/ParecerServiceImpl.java
- aplicacao/gpa-extensao/src/main/java/ufc/quixada/npi/gpa/util/Constants.java
- aplicacao/gpa-extensao/src/main/java/ufc/quixada/npi/gpa/util/PersonalConstants.java
- aplicacao/gpa-extensao/src/main/resources/static/gpa/coordenacao/submeterAcao.js
- aplicacao/gpa-extensao/src/main/resources/templates/coordenacao/submissao/submeter.html
- aplicacao/gpa-extensao/src/main/resources/templates/detalhes/acao/detalhes.html
Foi corrigido o bug e foram feitas algumas outras correções.
> EXT80 - Bug editar ação

- aplicacao/gpa-extensao/src/main/resources/static/gpa/coordenacao/participacao.js
- aplicacao/gpa-extensao/src/main/resources/templates/detalhes/acao/detalhes.html
resetar todos os campos do formulário
resetar validação do bootstrap validator após submissão
mostrar mensagem de erro ou sucesso centralizado no topo do card
> fechar formulario após submissão

- aplicacao/gpa-extensao/src/main/resources/static/gpa/coordenacao/listagem.js
- aplicacao/gpa-extensao/src/main/resources/static/gpa/direcao/index.js
- aplicacao/gpa-extensao/src/main/resources/templates/direcao/index.html
- aplicacao/gpa-extensao/src/main/resources/templates/principal/index.html
Foi implementada a animação no estilo fade para a listagem das ações da
coordenação e da direção.
> Animação da listagem de ações

- aplicacao/gpa-extensao/src/main/java/ufc/quixada/npi/gpa/repository/AcaoExtensaoRepository.java
- aplicacao/gpa-extensao/src/main/resources/templates/principal/index.html
mostrar nome do coordenador da acão da participação
> trazer somente acões que pessoa não coordena

- aplicacao/gpa-extensao/src/main/java/ufc/quixada/npi/gpa/controller/AdministracaoController.java
- aplicacao/gpa-extensao/src/main/java/ufc/quixada/npi/gpa/controller/BolsaController.java
- aplicacao/gpa-extensao/src/main/java/ufc/quixada/npi/gpa/controller/ExtensaoController.java
- aplicacao/gpa-extensao/src/main/java/ufc/quixada/npi/gpa/model/Bolsa.java
- aplicacao/gpa-extensao/src/main/java/ufc/quixada/npi/gpa/model/FrequenciaBolsista.java
- aplicacao/gpa-extensao/src/main/java/ufc/quixada/npi/gpa/repository/BolsaRepository.java
- aplicacao/gpa-extensao/src/main/java/ufc/quixada/npi/gpa/service/AcaoExtensaoService.java
- aplicacao/gpa-extensao/src/main/java/ufc/quixada/npi/gpa/service/impl/AcaoExtensaoServiceImpl.java
- aplicacao/gpa-extensao/src/main/java/ufc/quixada/npi/gpa/util/Constants.java
- aplicacao/gpa-extensao/src/main/resources/templates/detalhes/acao/detalhes.html
Ação Extensão pode ser encerrada por um ADMIN. As bolsas vinculadas a essa ação serão inativadas após encerramento da ação.
> Ext 100 encerrar acao extensao

- aplicacao/gpa-extensao/src/main/java/ufc/quixada/npi/gpa/model/Aluno.java
- aplicacao/gpa-extensao/src/main/java/ufc/quixada/npi/gpa/model/AlunoEntityListener.java
- aplicacao/gpa-extensao/src/main/java/ufc/quixada/npi/gpa/model/Pessoa.java
- aplicacao/gpa-extensao/src/main/java/ufc/quixada/npi/gpa/model/PessoaEntityListener.java
- aplicacao/gpa-extensao/src/main/java/ufc/quixada/npi/gpa/model/Servidor.java
- aplicacao/gpa-extensao/src/main/java/ufc/quixada/npi/gpa/model/ServidorEntityListener.java
- aplicacao/gpa-extensao/src/main/resources/application.properties
Utilizando serviço LDAP para completar informações de alunos, servidores, ou uma pessoa.
> Ext 106 ldap

- aplicacao/gpa-extensao/src/main/java/ufc/quixada/npi/gpa/controller/ParticipacaoController.java
> comparar o id do participante com o id do coordenador da ação no lugar

- aplicacao/gpa-extensao/src/main/java/ufc/quixada/npi/gpa/validator/BolsaValidator.java
- aplicacao/gpa-extensao/src/main/resources/static/gpa/administracao/cadastro.js
- aplicacao/gpa-extensao/src/main/resources/static/gpa/coordenacao/bolsa.js
correções na validação de adição de nova bolsa
não mudar valor do checkbox ao clicar em cancelar encerramento
> mostrar campos ao editar ação de Curso e de Evento

- aplicacao/gpa-extensao/src/main/java/ufc/quixada/npi/gpa/service/impl/BolsaServiceImpl.java
- aplicacao/gpa-extensao/src/main/resources/templates/administracao/bolsa/bolsistas.html
Foi implementada a mudança solicitada. Agora a frequência pode ser
modificada mesmo depois de o bolsista estar inativo.
> EXT-140 Permitir alterar entrega da frequência

- aplicacao/gpa-extensao/src/main/java/ufc/quixada/npi/gpa/controller/AlunoController.java
- aplicacao/gpa-extensao/src/main/java/ufc/quixada/npi/gpa/controller/ServidorController.java
- aplicacao/gpa-extensao/src/main/java/ufc/quixada/npi/gpa/model/Servidor.java
- aplicacao/gpa-extensao/src/main/java/ufc/quixada/npi/gpa/repository/ServidorRepository.java
- aplicacao/gpa-extensao/src/main/java/ufc/quixada/npi/gpa/service/AlunoService.java
- aplicacao/gpa-extensao/src/main/java/ufc/quixada/npi/gpa/service/ServidorService.java
- aplicacao/gpa-extensao/src/main/java/ufc/quixada/npi/gpa/service/impl/AlunoServiceImpl.java
- aplicacao/gpa-extensao/src/main/java/ufc/quixada/npi/gpa/service/impl/ServidorServiceImpl.java
- aplicacao/gpa-extensao/src/main/java/ufc/quixada/npi/gpa/util/Constants.java
- aplicacao/gpa-extensao/src/main/resources/static/gpa/administracao/cadastro-servidor.js
- aplicacao/gpa-extensao/src/main/resources/static/gpa/modulos/authentication.js
- aplicacao/gpa-extensao/src/main/resources/static/gpa/modulos/menu.js
- aplicacao/gpa-extensao/src/main/resources/templates/administracao/cadastro-servidor/cadastro-servidor.html
- aplicacao/gpa-extensao/src/main/resources/templates/modulos/fragments.html
Implementado o cadastro de servidor, além de melhorias no cadastro de aluno.
> Ext 141 cadastro servidor

- aplicacao/gpa-extensao/src/main/java/ufc/quixada/npi/gpa/config/GpaExtensaoSecurity.java
- aplicacao/gpa-extensao/src/main/java/ufc/quixada/npi/gpa/controller/AlunoController.java
- aplicacao/gpa-extensao/src/main/java/ufc/quixada/npi/gpa/controller/BuscarController.java
- aplicacao/gpa-extensao/src/main/java/ufc/quixada/npi/gpa/service/impl/AcaoExtensaoServiceImpl.java
- aplicacao/gpa-extensao/src/main/java/ufc/quixada/npi/gpa/service/impl/AlunoServiceImpl.java
- aplicacao/gpa-extensao/src/main/java/ufc/quixada/npi/gpa/specification/AcaoExtensaoEspecification.java
- aplicacao/gpa-extensao/src/main/java/ufc/quixada/npi/gpa/util/Constants.java
- aplicacao/gpa-extensao/src/main/java/ufc/quixada/npi/gpa/validator/BolsaValidator.java
- aplicacao/gpa-extensao/src/main/resources/templates/buscar/acao-extensao.html
- aplicacao/gpa-extensao/src/main/resources/templates/detalhes/bolsista/detalhes-bolsista.html
EXT-153-Colocar label em vermelho na página de detalhe do bolsista quando ele estiver inativo na ação de extensão
EXT-155-Alterar texto 'coordenador' para 'servidor' na página de busca
de ações;
Resolvendo issues do Codacy.
> EXT-153 e EXT-155

- aplicacao/gpa-extensao/src/main/java/ufc/quixada/npi/gpa/controller/ParecerController.java
- aplicacao/gpa-extensao/src/main/java/ufc/quixada/npi/gpa/model/Parecer.java
- aplicacao/gpa-extensao/src/main/java/ufc/quixada/npi/gpa/service/ParecerService.java
- aplicacao/gpa-extensao/src/main/java/ufc/quixada/npi/gpa/service/impl/ParecerServiceImpl.java
- aplicacao/gpa-extensao/src/main/resources/static/gpa/direcao/detalhes.js
- aplicacao/gpa-extensao/src/main/resources/templates/detalhes/acao/fragments-detalhes-parecer.html
Agora não existe mais a funcionalidade de fazer upload de arquivos na
emissão do parecer.
> Remoção do upload de arquivos do parecer.

- aplicacao/gpa-extensao/src/main/java/ufc/quixada/npi/gpa/service/impl/AcaoExtensaoServiceImpl.java
- aplicacao/gpa-extensao/src/main/resources/application-dev.properties
- aplicacao/gpa-extensao/src/main/resources/application.properties
> Definição de arquivos de configuração de ambientes de desenvolvimento,

- aplicacao/gpa-extensao/src/main/resources/templates/acao/visualizar-acao.html
Corração da não exclusão da parceria
> Correção na exclusão de uma parceria

- aplicacao/gpa-extensao/src/main/resources/templates/acao/cadastrar-acao.html
- aplicacao/gpa-extensao/src/main/resources/templates/acao/detalhes/detalhes-dados-basicos.html
- aplicacao/gpa-extensao/src/main/resources/templates/acao/detalhes/detalhes-equipe.html
- aplicacao/gpa-extensao/src/main/resources/templates/acao/detalhes/detalhes-parcerias.html
- aplicacao/gpa-extensao/src/main/resources/templates/acao/detalhes/detalhes-parecer-relator.html
- aplicacao/gpa-extensao/src/main/resources/templates/aluno/listar-alunos.html
- aplicacao/gpa-extensao/src/main/resources/templates/base/menu.html
- aplicacao/gpa-extensao/src/main/resources/templates/buscar/acao-extensao.html
- aplicacao/gpa-extensao/src/main/resources/templates/detalhes/acao/detalhes.html
- aplicacao/gpa-extensao/src/main/resources/templates/detalhes/acao/fragment-form-bolsa.html
- aplicacao/gpa-extensao/src/main/resources/templates/detalhes/acao/fragment-form-participacao.html
- aplicacao/gpa-extensao/src/main/resources/templates/detalhes/acao/fragmento-parceria-externa.html
- aplicacao/gpa-extensao/src/main/resources/templates/detalhes/acao/fragments-detalhes-homologacao.html
- aplicacao/gpa-extensao/src/main/resources/templates/detalhes/acao/fragments-detalhes-parecer.html
- aplicacao/gpa-extensao/src/main/resources/templates/servidor/listar-servidores.html
Resolve problema de active duplicado no menu nav bar e altera as cores dos botoes de primary para info
> #211 transformar card submenu
